### ISSUE TITLE
Setting the currency to track

### ISSUE THREAD

**Issue by sskras** [trevtravtrev/CryptoPortfolioTracker#2]
Hello. Since there is no discussion tab enabled for this repo, I am going to ask here:

How does the tool knows names and amount of tracked currency, please?

I skimmed over the README and see no hints about setting that.

**Comment by trevtravtrev** [comment]
You set them in the config.py settings file.

**Comment by sskras** [comment]
So it's here, Eg: https://github.com/trevtravtrev/CoinSense/blob/main/coinsense/config.py#L17

Thanks.
